# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u171-jdk
      - image: circleci/mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD: password
        - MYSQL_DATABASE: stocks
        - MYSQL_USER: monty
        - MYSQL_PASSWORD: some_pass
   
    working_directory: ~/Web-Application

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx6656m
    
    steps:
      - checkout

      - run: sudo apt install -y mysql-client

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
        
      # run tests!
      - run: mvn test

